# Generated by Django 3.2 on 2022-12-07 12:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('fastfood', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 7, 12, 15, 46, 550951, tzinfo=utc), verbose_name='Time of oder'),
        ),
    ]
