# Generated by Django 3.2 on 2022-12-07 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fastfood', '0002_alter_order_order_date_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='zakaz',
        ),
        migrations.AddField(
            model_name='food',
            name='booking',
            field=models.ManyToManyField(related_name='meal', through='fastfood.Order', to='fastfood.Ingredient'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Time of oder'),
        ),
    ]
